<a href="https://colab.research.google.com/github/baz-l/Machine-Learning/blob/main/Diabetes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
df=pd.read_csv("/content/diabetes.csv")
df


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

SIZE

In [ ]:
print(df.size)

6912


SHAPE

In [ ]:
print(df.shape)

(768, 9)


HEAD

In [ ]:
print(df.head(5))

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  


TAIL

In [ ]:
print(df.tail(5))

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  


COLUMNS

In [ ]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

NUMBER OF MISSING VALUES

In [ ]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

TO FIND COUNT OF UNIQUE VALUES IN A COLOUMN

In [ ]:
df['Outcome'].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

SPLITTING INPUT AND OUTPUT VALUES

In [ ]:
x=df[['Pregnancies','Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age']]
x


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [ ]:
x=df.iloc[:,:-1]

In [ ]:
y=df[['Outcome']]
y

Outcome
0          1
1          0
2          1
3          0
4          1
..       ...
763        0
764        0
765        0
766        1
767        0

[768 rows x 1 columns]

In [ ]:
y=df.iloc[:,-1]
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

TRAIN TEST SPLIT

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30)

In [ ]:
x_train

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
311            0      106             70             37      148  39.4   
20             3      126             88             41      235  39.3   
590           11      111             84             40        0  46.8   
135            2      125             60             20      140  33.8   
480            3      158             70             30      328  35.5   
..           ...      ...            ...            ...      ...   ...   
677            0       93             60              0        0  35.3   
408            8      197             74              0        0  25.9   
141            5      106             82             30        0  39.5   
110            3      171             72             33      135  33.3   
722            1      149             68             29      127  29.3   

     DiabetesPedigreeFunction  Age  
311                     0.605   22  
20                      0.704   27  
590                     0.925   45  
135                     0.088   31  
480                     0.344   35  
..                        ...  ...  
677                     0.263   25  
408                     1.191   39  
141                     0.286   38  
110                     0.199   24  
722                     0.349   42  

[537 rows x 8 columns]

In [ ]:
y_train

311    0
20     0
590    1
135    0
480    1
      ..
677    0
408    1
141    0
110    1
722    1
Name: Outcome, Length: 537, dtype: int64

In [ ]:
x_test

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
30             5      109             75             26        0  36.0   
288            4       96             56             17       49  20.8   
157            1      109             56             21      135  25.2   
234            3       74             68             28       45  29.7   
760            2       88             58             26       16  28.4   
..           ...      ...            ...            ...      ...   ...   
741            3      102             44             20       94  30.8   
615            3      106             72              0        0  25.8   
575            1      119             44             47       63  35.5   
62             5       44             62              0        0  25.0   
479            4      132             86             31        0  28.0   

     DiabetesPedigreeFunction  Age  
30                      0.546   60  
288                     0.340   26  
157                     0.833   23  
234                     0.293   23  
760                     0.766   22  
..                        ...  ...  
741                     0.400   26  
615                     0.207   27  
575                     0.280   25  
62                      0.587   36  
479                     0.419   63  

[231 rows x 8 columns]

In [ ]:
y_test

30     0
288    0
157    0
234    0
760    0
      ..
741    0
615    0
575    0
62     0
479    0
Name: Outcome, Length: 231, dtype: int64

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler() #scaler is a variable


In [ ]:
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

MODEL CREATION

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=7)

In [ ]:
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=7)

In [ ]:
pred=knn.predict([[5,96,74,18,67,33.6,0.997,43]])
pred

array([1])

In [ ]:
y_pred=knn.predict(x_test)
y_pred

array([1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1])

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [ ]:
mat=confusion_matrix(y_pred,y_test)
mat

array([[138,  38],
       [ 20,  35]])

In [ ]:
score=accuracy_score(y_pred,y_test)
score

0.7489177489177489