<a href="https://colab.research.google.com/github/baz-l/Machine-Learning/blob/main/Polynomial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("/content/polynomial.csv")
df

sno  Temperature  Pressure
0    1            0    0.0002
1    2           20    0.0012
2    3           40    0.0060
3    4           60    0.0300
4    5           80    0.0900
5    6          100    0.2700

In [ ]:
df.size

18

In [ ]:
df.shape

(6, 3)

In [ ]:
df.columns

Index(['sno', 'Temperature', 'Pressure'], dtype='object')

In [ ]:
df.head()

sno  Temperature  Pressure
0    1            0    0.0002
1    2           20    0.0012
2    3           40    0.0060
3    4           60    0.0300
4    5           80    0.0900

In [ ]:
df.tail()

sno  Temperature  Pressure
1    2           20    0.0012
2    3           40    0.0060
3    4           60    0.0300
4    5           80    0.0900
5    6          100    0.2700

In [ ]:
x=df.iloc[:,:-1]
x

sno  Temperature
0    1            0
1    2           20
2    3           40
3    4           60
4    5           80
5    6          100

In [ ]:
y=df.iloc[:,-1]
y

0    0.0002
1    0.0012
2    0.0060
3    0.0300
4    0.0900
5    0.2700
Name: Pressure, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.30,random_state=1)
x_train

sno  Temperature
4    5           80
0    1            0
3    4           60
5    6          100

In [ ]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array([0.05259286, 0.00763571])

In [ ]:
print(f"Slope is {model.coef_}")

Slope is [0.00011211 0.00224225]


In [ ]:
print(f"Constant is {model.intercept_}")

Constant is -0.0374335411471321


In [ ]:
from sklearn.metrics import mean_absolute_error
print(mean_absolute_error(y_pred,y_test))

0.026514285714285737


In [ ]:
from sklearn.metrics import r2_score
print(r2_score(y_pred,y_test))

-1.1891681103323086


In [ ]:
from sklearn.preprocessing import PolynomialFeatures

In [ ]:
poly=PolynomialFeatures(degree=3)

In [ ]:
x_poly=poly.fit_transform(x)
x_poly

array([[1.00e+00, 1.00e+00, 0.00e+00, 1.00e+00, 0.00e+00, 0.00e+00,
        1.00e+00, 0.00e+00, 0.00e+00, 0.00e+00],
       [1.00e+00, 2.00e+00, 2.00e+01, 4.00e+00, 4.00e+01, 4.00e+02,
        8.00e+00, 8.00e+01, 8.00e+02, 8.00e+03],
       [1.00e+00, 3.00e+00, 4.00e+01, 9.00e+00, 1.20e+02, 1.60e+03,
        2.70e+01, 3.60e+02, 4.80e+03, 6.40e+04],
       [1.00e+00, 4.00e+00, 6.00e+01, 1.60e+01, 2.40e+02, 3.60e+03,
        6.40e+01, 9.60e+02, 1.44e+04, 2.16e+05],
       [1.00e+00, 5.00e+00, 8.00e+01, 2.50e+01, 4.00e+02, 6.40e+03,
        1.25e+02, 2.00e+03, 3.20e+04, 5.12e+05],
       [1.00e+00, 6.00e+00, 1.00e+02, 3.60e+01, 6.00e+02, 1.00e+04,
        2.16e+02, 3.60e+03, 6.00e+04, 1.00e+06]])

In [ ]:
poly.fit(x_poly,y)

PolynomialFeatures(degree=3)

In [ ]:
model1=LinearRegression()

In [ ]:
model1.fit(x_poly,y)

LinearRegression()

In [ ]:
y_poly=model1.predict(x_poly)

In [ ]:
y_poly

array([-0.00198889,  0.00724444,  0.00371111,  0.02248889,  0.09865556,
        0.26728889])

In [ ]:
from sklearn.metrics import accuracy_score

# Assuming y_pred and y_test are your predicted and true labels
y_pred = model.predict(x_test)  # Replace with your actual prediction code

# Convert to integers if needed
y_pred = y_pred.astype(int)
y_test = y_test.astype(int)

# Calculate accuracy
score = accuracy_score(y_pred, y_test)
print(f"Accuracy: {score}")


Accuracy: 1.0
